"""
Generate synthetic university academic integrity policy PDFs for AIRA demo testing.

Run:  python generate_synthetic_pdfs.py
Output: data/policies/  (4 new PDFs)
"""

from fpdf import FPDF

POLICIES = {
    "stanford_integrity.pdf": {
        "university": "Stanford University",
        "title": "Honor Code and Academic Integrity Policy",
        "version": "August 2024 Edition",
        "sections": [
            ("1. Preamble", [
                "Stanford University is committed to the highest standards of academic integrity. "
                "All members of the Stanford community - students, faculty, and staff - are expected "
                "to uphold these principles in every academic endeavor.",

                "The Stanford Honor Code applies to all coursework submitted for academic credit, "
                "including examinations, papers, problem sets, programming assignments, and any "
                "other evaluative materials as determined by the instructor.",

                "Violations of this policy will be adjudicated by the Stanford Office of Community "
                "Standards in accordance with procedures outlined in the Student Conduct Process "
                "handbook. Sanctions may include, but are not limited to, course failure, suspension, "
                "or permanent separation from the university.",
            ]),
            ("2. Prohibited Conduct", [
                "Cheating is defined as the use of unauthorized materials, information, or study aids "
                "in any academic exercise. Students are responsible for understanding what constitutes "
                "authorized materials in each course context.",

                "Plagiarism includes representing another's work, words, or ideas as one's own "
                "without appropriate attribution, whether from published sources, online repositories, "
                "peers, or any automated system.",

                "Fabrication refers to the falsification or invention of any information or citation "
                "in an academic exercise.",

                "Facilitating academic dishonesty includes knowingly helping or attempting to help "
                "another individual commit a violation of this policy.",

                "Multiple submission is the submission of work previously submitted for credit in "
                "another course without prior written approval from the current course instructor.",
            ]),
            ("3. Artificial Intelligence and Automated Tools", [
                "The use of artificial intelligence tools, including large language models, generative "
                "AI platforms, and automated writing assistants, is governed by individual course "
                "policies established by the instructor of record.",

                "In the absence of explicit instructor guidance, students should assume that AI-assisted "
                "work is subject to the same attribution requirements as any other external source. "
                "Work substantially generated by an AI system without meaningful student transformation "
                "may constitute plagiarism.",

                "Students who use AI tools to brainstorm, outline, or refine their own work are "
                "encouraged - but not required - to disclose such use in a brief author's note. The "
                "threshold for 'substantial' AI contribution is not defined and will be assessed "
                "case-by-case by the course instructor.",

                "AI-generated code submitted as original student work in computer science courses "
                "is prohibited unless the assignment explicitly designates AI assistance as permitted. "
                "Detection of AI-generated code may rely on automated tools whose accuracy is not "
                "guaranteed.",

                "Oral examinations or viva voce assessments may be used to verify authorship of "
                "submitted AI-assisted work at instructor discretion.",
            ]),
            ("4. Collaboration Policy", [
                "Unless an assignment is explicitly designated as a group project, all work submitted "
                "must represent the student's independent effort.",

                "Discussion of course material with peers is encouraged. However, students must "
                "ensure that submitted work is produced independently and reflects their own "
                "understanding, even when collaboration in the learning process has occurred.",

                "What constitutes impermissible collaboration versus acceptable peer discussion "
                "is determined by the course instructor. When in doubt, students should seek "
                "clarification before collaborating.",

                "Remote collaboration - including collaboration via online forums, messaging platforms, "
                "or code-sharing repositories - is subject to the same standards as in-person collaboration.",
            ]),
            ("5. Reporting and Adjudication", [
                "Faculty members who suspect a violation must report the incident to the Office of "
                "Community Standards within a reasonable time after discovery. No specific deadline "
                "is mandated by this policy.",

                "Students accused of academic misconduct will be notified in writing and afforded "
                "the opportunity to respond before any final determination is made.",

                "The Office of Community Standards may impose interim measures, including grade "
                "withholding, pending resolution of a reported violation.",

                "Appeals of misconduct findings may be submitted to the Academic Appeals Panel "
                "within thirty (30) days of the written decision. The Panel's determination is "
                "final and not subject to further internal review.",
            ]),
            ("6. Citation and Attribution", [
                "All sources of ideas, data, analysis, or language incorporated into submitted "
                "work must be cited according to the citation format specified by the instructor "
                "or, in the absence of such specification, according to the disciplinary norm "
                "of the relevant field.",

                "Self-citation - the attribution of a student's own previously submitted or "
                "published work - is required when that work is incorporated into a new submission. "
                "Failure to self-cite may constitute plagiarism.",
            ]),
        ],
    },

    "uchicago_integrity.pdf": {
        "university": "University of Chicago",
        "title": "Academic Integrity Policy and Procedures",
        "version": "Effective Autumn Quarter 2024",
        "sections": [
            ("I. Statement of Principles", [
                "The University of Chicago holds academic integrity to be fundamental to the "
                "scholarly enterprise. Honest inquiry, rigorous citation, and independent "
                "intellectual effort are not merely rules but constitutive values of this institution.",

                "This policy applies to all students enrolled in degree programs, certificate "
                "programs, and non-degree coursework offered through any division or professional "
                "school of the University.",

                "Enforcement of this policy is a shared responsibility. Instructors, teaching "
                "assistants, department chairs, and academic deans all bear obligations to "
                "report and act on suspected violations. Failure to report a known violation "
                "may itself constitute a breach of community standards.",
            ]),
            ("II. Definitions", [
                "Academic dishonesty includes cheating, plagiarism, fabrication, and any other "
                "conduct that misrepresents the origin, extent, or nature of a student's academic work.",

                "Cheating means using or attempting to use unauthorized resources or assistance "
                "during an academic exercise. Resources are unauthorized if they are not explicitly "
                "permitted by the instructor.",

                "Plagiarism is the unattributed use of another's ideas, words, data, code, images, "
                "or other creative or intellectual output. Attribution is required regardless of "
                "the source: published works, unpublished works, internet sources, peer work, "
                "or outputs of automated systems.",

                "'Automated systems' as used in this policy includes, without limitation, "
                "AI language models, code autocomplete systems, paraphrasing tools, and "
                "translation software. This definition may be updated without notice as "
                "technology evolves.",

                "Fabrication means reporting data, results, or sources that do not exist or "
                "were not consulted.",
            ]),
            ("III. Artificial Intelligence Policy", [
                "Generative artificial intelligence tools may be used in coursework only when "
                "the instructor has granted explicit written permission. Verbal permission is "
                "not sufficient.",

                "Permitted AI use must be documented. Students who receive permission to use "
                "AI tools must maintain a log of all AI interactions relevant to the submission "
                "and make that log available to the instructor upon request. The log format "
                "is not specified by this policy.",

                "Even where AI use is permitted, students remain responsible for the accuracy, "
                "integrity, and academic quality of submitted work. Submission of AI-generated "
                "content that contains factual errors, unsupported claims, or fabricated citations "
                "is a violation of this policy irrespective of permitted tool use.",

                "AI detection software may be used to flag suspected AI-assisted submissions. "
                "A positive result from detection software creates a rebuttable presumption "
                "of policy violation but is not, standing alone, conclusive proof of misconduct. "
                "The threshold sensitivity settings for such software are not disclosed.",

                "Courses designated as 'AI-integrated' may require the use of specific AI tools "
                "as part of the learning objectives. In such courses, the course syllabus governs "
                "permissible use and supersedes this policy to the extent of any conflict.",
            ]),
            ("IV. Investigation Procedures", [
                "When an instructor suspects a violation, the instructor shall notify the student "
                "and the Dean of Students office simultaneously. The instructor shall not impose "
                "a grade penalty prior to the completion of the formal review process.",

                "The Dean of Students office will appoint an Academic Integrity Officer to "
                "conduct a preliminary assessment within ten (10) business days of receiving "
                "the report.",

                "If the preliminary assessment supports a finding of probable cause, the matter "
                "will be referred to an Academic Integrity Hearing Panel. The Panel consists of "
                "three faculty members drawn from a standing roster. Student representation "
                "on the Panel is advisory and non-voting.",

                "Hearings shall be conducted in a manner that protects the privacy of both "
                "the accused student and any witnesses. Recordings of hearings are retained "
                "by the Dean of Students office and are not accessible to the parties "
                "except upon order of a reviewing authority.",

                "Sanctions imposed by the Hearing Panel may include: written warning, required "
                "completion of an academic integrity module, grade penalty, course failure, "
                "transcript notation, suspension, or expulsion.",
            ]),
            ("V. Special Circumstances", [
                "Group projects present particular challenges for attribution. Each student "
                "in a group project is jointly and severally responsible for the integrity "
                "of the entire submission unless a documented division of labor has been "
                "approved in advance by the instructor.",

                "Resubmission of prior work for new credit is prohibited without advance written "
                "approval. Students who wish to build on prior work must disclose this to "
                "the instructor and receive explicit permission before submission.",

                "Collaboration with individuals outside the University - including online tutoring "
                "services, professional editors, and AI tool operators - is subject to the "
                "same attribution requirements as collaboration within the University community.",
            ]),
        ],
    },

    "cmu_integrity.pdf": {
        "university": "Carnegie Mellon University",
        "title": "Policy on Academic Integrity",
        "version": "Spring 2024  -  Applies to All Colleges",
        "sections": [
            ("Section 1: Purpose and Scope", [
                "Carnegie Mellon University's Policy on Academic Integrity is designed to protect "
                "the fairness of academic evaluation, the value of CMU credentials, and the "
                "intellectual environment of the university.",

                "This policy applies to all students, including undergraduate, graduate, and "
                "doctoral students, in all colleges and programs of the university. It applies "
                "to all submitted academic work regardless of format: written, oral, computational, "
                "or otherwise.",

                "Each college may adopt supplemental policies consistent with this policy. "
                "In case of conflict, the more restrictive provision applies. College-specific "
                "policies must be published and made accessible to students prior to the "
                "relevant academic term.",
            ]),
            ("Section 2: Violations", [
                "Unauthorized assistance means receiving help on academic work from any source "
                "not explicitly authorized by the instructor. This includes, but is not limited to, "
                "assistance from other students, tutors, online services, and AI systems.",

                "Misrepresentation of authorship means claiming, implying, or allowing a false "
                "impression that work was performed by the submitting student when material "
                "contributions were made by others.",

                "Unauthorized collaboration occurs when students work together on assignments "
                "designated as individual work. The determination of what constitutes 'working "
                "together' is made by the instructor and may vary by assignment.",

                "Tampering means altering graded work before resubmission for regrading purposes.",

                "Unauthorized access to examination content includes obtaining, transmitting, "
                "or possessing examination questions, answers, or any information about an "
                "examination before it is administered.",
            ]),
            ("Section 3: AI and Computational Tools", [
                "CMU recognizes that artificial intelligence tools are rapidly changing the "
                "landscape of academic work. This section provides a framework; instructors "
                "have authority to adopt stricter or more permissive policies within their courses.",

                "Category A  -  Prohibited by Default: Submission of text, code, data analysis, "
                "or other work generated by AI tools without attribution, where the instructor "
                "has not authorized such tools, constitutes misrepresentation of authorship.",

                "Category B  -  Permitted with Disclosure: Where an instructor permits AI tool "
                "use, students must disclose such use in a standardized disclosure statement "
                "attached to the submission. The format of the disclosure statement will be "
                "provided by the instructor or, if not provided, students may use any format "
                "that clearly identifies the tool, the nature of its use, and the student's "
                "own intellectual contribution.",

                "Category C  -  Required Use: Some courses may require the use of AI tools. "
                "In such courses, the course syllabus governs all aspects of permissible "
                "and required AI use.",

                "The boundary between 'substantially AI-generated' and 'AI-assisted' work "
                "is not defined numerically. Instructors exercise judgment in making this "
                "determination, and their assessments are presumed valid in the absence "
                "of clear error.",

                "Automated AI detection tools may be used by instructors but do not constitute "
                "definitive evidence of policy violation. Students have the right to respond "
                "to detection results before any penalty is imposed.",

                "Computational tools that perform analysis, formatting, or error-checking "
                "are generally permitted unless the course explicitly prohibits them. "
                "The distinction between a 'computational tool' and an 'AI tool' is not "
                "defined in this policy.",
            ]),
            ("Section 4: Procedure", [
                "Instructors who believe a violation has occurred must report the incident "
                "to the Academic Integrity Office using the official reporting form within "
                "two (2) weeks of discovery.",

                "Upon receipt of a report, the Academic Integrity Office will notify the "
                "student within five (5) business days. Students are entitled to a hearing "
                "if they contest the finding.",

                "Hearings are conducted by the Academic Review Board, which consists of "
                "faculty and student members. The composition of the Board for a specific "
                "hearing is determined by the Academic Integrity Office.",

                "The standard of proof for finding a violation is clear and convincing evidence. "
                "The burden of proof rests with the university.",

                "Sanctions are scaled to the severity of the violation and the student's "
                "disciplinary history. First-time violations in good faith typically result "
                "in educational remediation rather than punitive sanctions, at the discretion "
                "of the Academic Review Board.",
            ]),
            ("Section 5: Records and Appeals", [
                "Records of substantiated violations are maintained in the student's disciplinary "
                "file for five (5) years after graduation or separation from the university, "
                "after which they are expunged unless a suspension or expulsion was imposed.",

                "Students may appeal a finding within fifteen (15) days of receiving the "
                "written decision. Appeals must be based on procedural error, new evidence, "
                "or demonstrably disproportionate sanction. Appeals are reviewed by the "
                "Provost's office or designee.",

                "An appeal does not automatically stay the imposition of a sanction. The "
                "reviewing authority may grant a stay upon good cause shown.",
            ]),
        ],
    },

    "columbia_integrity.pdf": {
        "university": "Columbia University",
        "title": "Academic Integrity and Community Standards Policy",
        "version": "Adopted by University Senate, September 2024",
        "sections": [
            ("Part A: Foundations", [
                "Columbia University's commitment to academic integrity derives from its mission "
                "as a research university: knowledge is advanced only through honest inquiry, "
                "transparent methodology, and rigorous attribution.",

                "This policy covers all academic work submitted in courses offered by Columbia "
                "University, including work submitted through third-party platforms, online "
                "portals, or submission systems operated by publishers or external vendors.",

                "This policy applies to all students regardless of degree level, residency status, "
                "or enrollment modality. Students enrolled in joint degree programs are also "
                "subject to the policies of their partner institutions and, in case of conflict, "
                "must comply with the stricter requirement.",
            ]),
            ("Part B: Core Obligations", [
                "Students must ensure that all submitted work is their own original work unless "
                "the assignment expressly permits collaboration or the use of external sources.",

                "All sources - primary, secondary, tertiary, and indirect - must be cited. An "
                "indirect source is one not consulted directly but referenced through another "
                "source. The appropriate level of attribution for indirect sources is governed "
                "by disciplinary convention and instructor guidance.",

                "Students are responsible for understanding the academic integrity expectations "
                "of each course. Claiming ignorance of a specific prohibition is not a defense "
                "to a violation, provided the prohibition was communicated in the course syllabus "
                "or by the instructor.",

                "Work submitted in one course may not be submitted for credit in another course "
                "without the explicit written consent of both instructors. This prohibition "
                "applies to partial submissions and substantially similar work.",
            ]),
            ("Part C: AI Usage and Generative Technology", [
                "Columbia University recognizes that generative AI tools, including large language "
                "models, image generators, code synthesis tools, and multimodal systems, represent "
                "a qualitative shift in the means by which academic work can be produced.",

                "The university adopts a course-level governance model for AI use: the instructor "
                "of each course has authority to permit, restrict, or require specific AI tool "
                "use, provided such policies are communicated to students in the course syllabus "
                "no later than the first meeting of the course.",

                "Where an instructor has not provided an explicit AI use policy by the first "
                "class meeting, the default is that all AI-assisted work must be attributed. "
                "Attribution means identifying the tool used, the nature of the interaction, "
                "and the extent of the AI's contribution to the final work product.",

                "Attribution of AI use is required but does not, by itself, render AI-assisted "
                "work compliant. Instructors may determine that attributed AI-generated work "
                "fails to meet the learning objectives of an assignment and may assign "
                "reduced or no credit accordingly.",

                "The university does not endorse or certify any specific AI detection tool. "
                "Instructors who rely on AI detection tools must disclose this practice in "
                "the course syllabus. Detection tool outputs may be used as one factor in "
                "an integrity review but may not be the sole basis for a finding of violation.",

                "Students who are uncertain whether a particular use of an AI tool is permissible "
                "are advised to seek advance clarification from the instructor. The burden "
                "of seeking clarification rests with the student.",

                "AI tools that access, retrieve, or generate information from the internet "
                "without citation are subject to the same attribution requirements as any "
                "internet source. Students are responsible for verifying the accuracy of "
                "AI-generated citations and content before submission.",

                "Voice assistants, autocomplete features in standard productivity software, "
                "and grammar checkers are excluded from this policy unless an instructor "
                "specifically designates them as restricted. The boundary between excluded "
                "and covered tools may shift as technology develops and will be clarified "
                "by policy updates as needed.",
            ]),
            ("Part D: Process", [
                "Reports of suspected violations must be submitted to the Office of Student "
                "Conduct within thirty (30) days of the date the instructor first had "
                "reason to suspect a violation. Reports submitted after this deadline "
                "may be declined at the discretion of the Director.",

                "Upon receiving a report, the Office of Student Conduct will initiate a "
                "preliminary inquiry within seven (7) business days. The preliminary "
                "inquiry is not adversarial; its purpose is to determine whether the "
                "report warrants a full hearing.",

                "Students are entitled to be accompanied by an advisor of their choosing, "
                "including an attorney, at all stages of the process. The university's "
                "obligations do not include providing an advisor.",

                "The Hearing Board consists of three tenured faculty members and two "
                "student representatives selected by the student government. The student "
                "representatives are voting members on questions of fact but not on "
                "questions of sanction.",

                "Findings of violation and associated sanctions are communicated in writing "
                "within five (5) business days of the hearing. The written decision "
                "constitutes the official record of the proceeding.",
            ]),
            ("Part E: Consequences", [
                "Sanctions range from a written warning to expulsion and may include academic "
                "probation, mandatory educational programming, grade penalties, course "
                "failure, transcript notation, suspension for one or more terms, or "
                "permanent separation from the university.",

                "Transcript notations for violations are recorded as 'Disciplinary Failure' "
                "or 'Disciplinary Suspension' as applicable and remain on the transcript "
                "for a period determined by the Hearing Board. The default retention "
                "period is five years; the Board may shorten or extend this period.",

                "Repeat violations result in presumptive escalation of sanctions. A second "
                "substantiated violation during enrollment presumptively warrants suspension; "
                "a third warrants expulsion. These presumptions may be overcome by a "
                "unanimous finding of exceptional mitigating circumstances.",
            ]),
        ],
    },
}


class PolicyPDF(FPDF):
    def __init__(self, university: str, title: str, version: str):
        super().__init__()
        self.university = university
        self.doc_title = title
        self.version = version
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(80, 80, 80)
        self.cell(0, 8, self.university, align="L")
        self.set_font("Helvetica", "", 8)
        self.cell(0, 0, self.version, align="R")
        self.ln(2)
        self.set_draw_color(160, 160, 160)
        self.set_line_width(0.3)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def title_block(self):
        self.ln(6)
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(20, 20, 20)
        self.multi_cell(0, 9, self.doc_title, align="C")
        self.ln(2)
        self.set_font("Helvetica", "", 11)
        self.set_text_color(60, 60, 60)
        self.cell(0, 7, self.university, align="C")
        self.ln(8)
        self.set_draw_color(40, 40, 40)
        self.set_line_width(0.6)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(6)

    def section_heading(self, text: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(20, 20, 100)
        self.multi_cell(0, 7, text)
        self.ln(1)
        self.set_draw_color(100, 100, 200)
        self.set_line_width(0.4)
        self.line(self.l_margin, self.get_y(), self.l_margin + 60, self.get_y())
        self.ln(3)

    def clause_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(30, 30, 30)
        self.multi_cell(0, 5.5, text)
        self.ln(3)


def build_pdf(filename: str, meta: dict, output_dir: str = "data/policies") -> str:
    pdf = PolicyPDF(meta["university"], meta["title"], meta["version"])
    pdf.add_page()
    pdf.title_block()

    for section_title, clauses in meta["sections"]:
        pdf.section_heading(section_title)
        for clause in clauses:
            pdf.clause_text(clause)

    out_path = f"{output_dir}/{filename}"
    pdf.output(out_path)
    return out_path


if __name__ == "__main__":
    import os
    os.makedirs("data/policies", exist_ok=True)
    for fname, meta in POLICIES.items():
        path = build_pdf(fname, meta)
        print(f"Generated: {path}")
    print("\nDone. 4 synthetic university PDFs written to data/policies/")
