"""Shared fixtures available to all test files.

A fixture is a reusable piece of test data or setup.
Instead of creating the same Clause object in 10 different tests,
you define it once here and pytest injects it automatically.
"""
import pytest
from backend.models import Clause, RiskAnnotation


@pytest.fixture
def sample_clause():
    """A realistic NEU policy clause for testing."""
    return Clause(
        id="test-id-001",
        text=(
            "Students are prohibited from submitting work that was generated "
            "by artificial intelligence tools without explicit faculty approval."
        ),
        source_doc="neu_academic_integrity.pdf",
        page_num=3,
        position_index=0,
        word_count=20,
    )


@pytest.fixture
def sample_annotation(sample_clause):
    """A realistic risk annotation for the sample clause."""
    return RiskAnnotation(
        clause_id=sample_clause.id,
        clause_text=sample_clause.text,
        risk_category="AIUsageLoophole",
        secondary_category=None,
        reasoning="The clause prohibits AI without defining what counts as AI-generated.",
        cited_text="generated by artificial intelligence tools",
        confidence=0.85,
        low_confidence_flag=False,
    )


@pytest.fixture
def none_annotation(sample_clause):
    """An annotation where no risk was found."""
    return RiskAnnotation(
        clause_id=sample_clause.id,
        clause_text=sample_clause.text,
        risk_category="None",
        secondary_category=None,
        reasoning="Clause is clear and enforceable.",
        cited_text="Students are prohibited",
        confidence=0.95,
        low_confidence_flag=False,
    )
